FROM python:3.9-slim

# 接收来自 docker-compose build.args 的参数
ARG HTTP_PROXY
ARG HTTPS_PROXY

# 将这些参数设置为构建过程中的环境变量
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}

WORKDIR /app

COPY requirements.txt .

# 现在这个 RUN 命令将会使用上面设置的代理
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-u", "DiscordMonitor.py"] 